import Head from 'next/head'
import { motion, AnimatePresence } from 'framer-motion'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'

export default function Page() {
  const router = useRouter()
  const [showinfo, setShowinfo] = useState(false)

  useEffect(() => {
    let time = 1500
    if (localStorage.getItem('visited') === '1') {
      setShowinfo(true)
      time = 60000
    }

    setTimeout(() => {
      localStorage.setItem('visited', '1')
      router.push('https://ptr.red/trr')
    }, time)
  }, [router])

  return (
    <div className='h-full bg-[#036b52] text-white flex flex-col items-center justify-center'>
      <Head>
        <title>Painel de Administração - Trybe</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='icon'
          href='https://assets-global.website-files.com/61549abf6fb9ca5e91bc5709/61549abf6fb9ca1534bc57a6_favicon-web.ico'
        />
      </Head>
      <h1 className='text-2xl font-black sr-only'>Painel de Administração</h1>
      <div className='flex flex-row gap-5 items-center'>
        <span aria-label='Trybe Icon'>
          <svg
            role='img'
            width='110'
            height='110'
            viewBox='0 0 110 110'
            fill='none'
            xmlns='http://www.w3.org/2000/svg'
            className='w-10'
          >
            <path
              d='M73.411 57.3242L90.9825 87.9534C92.0161 89.6937 93.3942 90.3905 95.1169 90.3905C97.5287 90.3905 99.9408 88.6499 99.9408 85.5173V24.2579C99.9408 21.1253 97.5287 19.3846 95.1169 19.3846C93.3942 19.3846 92.0161 20.0804 90.9825 21.8207L73.411 52.4509C73.0664 53.1471 72.7219 54.1909 72.7219 54.8871C72.7219 55.5832 72.7219 56.28 73.411 57.3242Z'
              fill='white'
            />
            <path
              d='M54.4571 67.1872L72.0326 98.3404C72.3773 99.0484 72.7219 100.111 72.7219 100.819C72.7219 103.651 70.3095 105.775 67.8971 105.775C67.2079 105.775 66.174 105.422 65.4848 105.067L12.4124 73.9133C10.6893 72.8512 10 71.0814 10 69.6654C10 67.1872 12.0681 64.355 14.8251 64.355L49.9766 64.7084C52.0443 64.7084 53.7678 65.4171 54.4571 67.1872Z'
              fill='white'
            />
            <path
              d='M49.9766 44.2367H14.8251C11.7235 44.2367 10 41.8089 10 39.3808C10 37.6465 10.6893 36.259 12.4124 35.2184L65.4848 4.69374C66.174 4.34687 67.2079 4 67.8971 4C70.6541 4 72.7219 6.42775 72.7219 8.85585C72.7219 9.54959 72.3773 10.5902 72.0326 11.2839L54.1121 41.8086C53.4228 43.5429 52.0443 44.2367 49.9766 44.2367Z'
              fill='white'
            />
          </svg>
        </span>
        <p className='text-xl font-bold'>Carregando...</p>
      </div>
      {showinfo && (
        <AnimatePresence>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className='font-mono absolute top-0 left-0 w-full h-full flex flex-col items-center justify-center text-center p-3'
          >
            <div className='max-w-xl flex flex-col items-center bg-black/60 backdrop-blur-sm rounded-md p-3'>
              <h2 className='text-xl font-bold mb-3'>1° de abril</h2>
              <p>Perdão, não podia deixar passar em vão.</p>
              <p>
                Fica tranquilo que não vou te redirecionar de novo e, se quiser
                o código-fonte tá no GitHub até sexta que vem.
              </p>
              <p>#VQV &#128154;</p>
              <a
                className='contents'
                href='https://github.com/peterfritz/april-fools-trybe'
                target='_blank'
                rel='noreferrer'
                onClick={(e) => {
                  setTimeout(() => {
                    router.push('https://ptr.red/trr')
                  }, 500)
                }}
              >
                <button className='bg-black py-2 px-4 mt-3 flex items-center justify-center gap-3 group hover:bg-white transition-all'>
                  <svg
                    role='img'
                    viewBox='0 0 24 24'
                    xmlns='http://www.w3.org/2000/svg'
                    className='shrink-0 h-6 w-6'
                  >
                    <path
                      className='fill-white group-hover:fill-black transition-all'
                      d='M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12'
                    />
                  </svg>
                  <span className='group-hover:text-black transition-all'>
                    Ver código no GitHub
                  </span>
                </button>
              </a>
            </div>
          </motion.div>
        </AnimatePresence>
      )}
    </div>
  )
}
